### ISSUE TITLE
frConomy ymsql cannot connect

### ISSUE THREAD

**Issue by a000a498** [Fr33styler/FrConomy#1]
i cannot connect to mysql ,others plugins still can

![image](https://user-images.githubusercontent.com/33992911/216402981-ffd6b2cd-931f-40b1-a2b8-6d505d611982.png)
![image](https://user-images.githubusercontent.com/33992911/216403192-a8d749e2-3892-4343-98ae-c1f1e1e9f8a2.png)

**Comment by a000a498** [comment]
> i cannot connect to mysql, thelabs also too 
> 
> ![image](https://user-images.githubusercontent.com/33992911/216402981-ffd6b2cd-931f-40b1-a2b8-6d505d611982.png) ![image](https://user-images.githubusercontent.com/33992911/216403192-a8d749e2-3892-4343-98ae-c1f1e1e9f8a2.png)

**Comment by Fr33styler** [comment]
Do you have a mysql server on ip 127.0.0.1 port 3306? It looks like you don't

**Comment by a000a498** [comment]
> Do you have a mysql server on ip 127.0.0.1 port 3306? It looks like you don't

yeah I'm sure i have , I have same problem with other plugin ,but some plugin can connect
![image](https://user-images.githubusercontent.com/33992911/216409406-b8031ca8-a7a9-48cf-899b-d8af5ce6468a.png)

**Comment by a000a498** [comment]
I had delete the wampserver twice time but still cannot connect :(

before re-install windows, sql works good

**Comment by a000a498** [comment]
> Do you have a mysql server on ip 127.0.0.1 port 3306? It looks like you don't

Will the MYSQL version affect the connection?

**Comment by a000a498** [comment]
> > Do you have a mysql server on ip 127.0.0.1 port 3306? It looks like you don't
> 
> Will the MYSQL version affect the connection?


ohh i change the mysql ver. to 5.7.40 then can works!!!

![image](https://user-images.githubusercontent.com/33992911/216414502-fc67940e-53a3-43b5-8657-b51eab1db0d8.png)
